adds lasagna
NUbots/GitDemos pull request #4
Opened 2021-03-26 01:52 UTC by stegglca

lasagna is good

2021-03-26 01:55 UTC, miikyla submitted a review, later dismissed
This is acceptable

2021-03-26 02:00 UTC, Bidski requested changes

2021-03-26 02:00 UTC, Bidski commented on Foods.yaml
> +  - ["pizza", "kale_smoothies"]
This is very wrong
```suggestion

  - [pizza", "kale_smoothies", "cheese", "pie", "lasagna"]
```

2021-03-26 02:00 UTC, moosahassanx approved these changes, later dismissed
I approve that lasagna is good 👍🏿

2021-03-27 03:35 UTC, KipHamiltons commented on Foods.yaml
> +  - ["pizza", "kale_smoothies", "cheese", "pie", "Carbonara", "Lasagna]
It was pointed out to me yesterday that we should try to stick with `snake_case` for `yaml` files
```suggestion
  - ["pizza", "kale_smoothies", "cheese", "pie", "carbonara", "lasagna]
```

2022-10-07 20:23 UTC, closed without merging